// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filemanager} from '../models';
import {settings} from '../models';
import {markdown} from '../models';

export function ClearRecentFiles():Promise<void>;

export function ExportDialog(arg1:string,arg2:string):Promise<void>;

export function ExportToHTML(arg1:string,arg2:string):Promise<void>;

export function ExportToPDF(arg1:string,arg2:string):Promise<void>;

export function GetCurrentFilePath():Promise<string>;

export function GetRecentFiles():Promise<Array<filemanager.RecentFile>>;

export function GetSettings():Promise<settings.UserSettings>;

export function GetTableOfContents(arg1:string):Promise<Array<markdown.TOCItem>>;

export function GetWordCount(arg1:string):Promise<markdown.Stats>;

export function OpenFile():Promise<string>;

export function OpenRecentFile(arg1:string):Promise<string>;

export function ReadFileByPath(arg1:string):Promise<string>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<string>;

export function SearchInDocument(arg1:string,arg2:string):Promise<Array<markdown.SearchResult>>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;

export function UpdateSettings(arg1:settings.UserSettings):Promise<void>;
