// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ExportContentToPDF(arg1) {
  return window['go']['main']['App']['ExportContentToPDF'](arg1);
}

export function ExportToHTML(arg1) {
  return window['go']['main']['App']['ExportToHTML'](arg1);
}

export function ExportToPDF(arg1) {
  return window['go']['main']['App']['ExportToPDF'](arg1);
}

export function GetCurrentFilePath() {
  return window['go']['main']['App']['GetCurrentFilePath']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTableOfContents(arg1) {
  return window['go']['main']['App']['GetTableOfContents'](arg1);
}

export function GetWordCount(arg1) {
  return window['go']['main']['App']['GetWordCount'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenRecentFile(arg1) {
  return window['go']['main']['App']['OpenRecentFile'](arg1);
}

export function ReadFileByPath(arg1) {
  return window['go']['main']['App']['ReadFileByPath'](arg1);
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}

export function SearchInDocument(arg1, arg2) {
  return window['go']['main']['App']['SearchInDocument'](arg1, arg2);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
